name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Cirno-Debug
          path: ${{github.workspace}}/app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Cirno-Release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          if-no-files-found: warn
